### ISSUE TITLE
Unable to save sprite file: "Fatal error: spawn ENOENT"

### ISSUE THREAD

**Issue by arlodesign** [nicholasstephan/grunt-spritesheet#1]
I'm trying to include grunt-spritesheet into a project started with Yeoman. Here's my task:

``` javascript
spritesheet: {
    build: {
        sprites: {
            'app/images/sprite.png': ['<%= yeoman.app %>/images/sprite/*.png']
        },
        sheet: '<%= yeoman.app %>/styles/sprite.css'
    }
}
```

When I run `grunt` or `grunt server` or any other target, I get the following error message:

```
Running "spritesheet:build" (spritesheet) task
Fatal error: spawn ENOENT
```

I thought maybe the issue was the yeoman.app variable. However, I added  `console.log(srcFiles);` into the top of the mkSprite() function in spritesheet.js, and all of the files in my /images/sprite/ folder were listed out.

Furthermore, when I change my image path to be '/images/bogus_dir/*.png' (so it doesn't find any images), the process doesn't fail and the CSS file gets written (though there's nothing in it but the media query). No sprite.png is created.

FWIW: I've been able to use grunt-spritesmith just fine. But since your task takes into account retina images, I'm hoping I can help get yours working. Thanks.

**Comment by nicholasstephan** [comment]
Your task looks good. 

Odd that grunt-spritesmith works while grunt-spritesheet doesn't as they're almost identical in the way they generate the images. I did find that grunt-spritesmith was using a different version of spritesmith, and have updated grunt-spritesheet to match.

I can't duplicate that error, so I'm not sure if that fixes the problem. Try installing the latest version and let me know how it goes.

Thanks.

**Comment by arlodesign** [comment]
That fixed it. Thank you!

**Comment by pichfl** [comment]
The reason for this error is a missing gfx library. grunt-spritesheet seems to default to imagemagick so if you get this plugin check if you have it installed.

If not and you're on a Mac, use Homebrew to install ist before running this task.
