### ISSUE TITLE
Getting error on grunt execute: “grunt.spritesheet requires a sprites and sheet property”

### ISSUE THREAD

**Issue by eschutho** [nicholasstephan/grunt-spritesheet#4]
I have the sprites and sheet properties listed in my main gruntfile: 
spritesheet: {
            // An array of filename / source images array pairs. The basename of the sprite file
            // is also prefixed to the CSS classes.
            sprites: {
                "images/icons/sprite.png": ['images/icons/*.png'],
            },
            // The destination for the build stylesheet
            sheet: "scss/homepsprite.css"
        },

Is there something that I'm missing? thank you. The load and register task scripts are all working fine and it runs with my other tasks.

**Comment by hereandnow** [comment]
grunt-spritesheet is a multitask which @implicitly iterates over all of its named sub-properties@.

you could see that grunt is probably trying to run "sprites" and "sheet" as a task:

Running "spritesheet:sprites" (spritesheet) task
that means that the documentation is somewhat not so clear, and you need a "name" for your task which could basically be anything (i use generate here):

<pre><code class="javascript">
spritesheet: {
  generate: {
    // An array of filename / source images array pairs. The basename of the sprite file
    // is also prefixed to the CSS classes.
    sprites: {
      "images/icons/sprite.png": ['images/icons/*.png']
    },
    // The destination for the build stylesheet
    sheet: "scss/homepsprite.css"
  }
}
</code></pre>

the output should now be:

Running "spritesheet:generate" (spritesheet) task

**Comment by jpdevries** [comment]
the docs should be updated because the example code there does not work
